import type { Metadata } from "next";
// todo: read about fonts load optimization
// fonts
import { Poppins } from "next/font/google";
// css
import "./globals.css";
// components
import { Footer } from "@/components/Footer";

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// todo: read about metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
